{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.firebase",
    "module": "firebase-crashlytics-gradle",
    "version": "2.9.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "firebase-crashlytics-gradle-2.9.5.jar",
          "url": "firebase-crashlytics-gradle-2.9.5.jar",
          "size": 8615592,
          "sha512": "4fe39c640fefc30af4cd609256f4cba7fbd77342846d2ed9436b627872d721e39130edd83ee0b3b0a7c78fc8496cb6926d4ecf66d650508eecb89a44aae571d1",
          "sha256": "5d8e68f40db9bd15a7205adebeed79301aa6f045d63469111b4e9a19d84cd532",
          "sha1": "5a57ad4b0a7f07d3f18efc0679365e336c4cbc2d",
          "md5": "381cf8f24936ee19b37cb5a5a339785b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-buildtools",
          "version": {
            "requires": "2.9.5"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-crashlytics-gradle-2.9.5.jar",
          "url": "firebase-crashlytics-gradle-2.9.5.jar",
          "size": 8615592,
          "sha512": "4fe39c640fefc30af4cd609256f4cba7fbd77342846d2ed9436b627872d721e39130edd83ee0b3b0a7c78fc8496cb6926d4ecf66d650508eecb89a44aae571d1",
          "sha256": "5d8e68f40db9bd15a7205adebeed79301aa6f045d63469111b4e9a19d84cd532",
          "sha1": "5a57ad4b0a7f07d3f18efc0679365e336c4cbc2d",
          "md5": "381cf8f24936ee19b37cb5a5a339785b"
        }
      ]
    }
  ]
}
