{
  "formatVersion": "1.1",
  "component": {
    "group": "com.virgilsecurity",
    "module": "ethree-common",
    "version": "2.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "gls4tuwsh5cexfdugromfow5wu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.virgilsecurity.sdk",
          "module": "sdk-android",
          "version": {
            "requires": "7.3.2"
          }
        },
        {
          "group": "com.virgilsecurity.sdk",
          "module": "crypto-android",
          "version": {
            "requires": "7.3.2"
          }
        },
        {
          "group": "com.virgilsecurity",
          "module": "pythia-android",
          "version": {
            "requires": "0.3.7"
          }
        },
        {
          "group": "com.virgilsecurity.crypto",
          "module": "pythia-android",
          "version": {
            "requires": "0.15.2"
          }
        },
        {
          "group": "com.virgilsecurity",
          "module": "ratchet-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "com.virgilsecurity",
          "module": "test-common",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ethree-common-2.0.9.aar",
          "url": "ethree-common-2.0.9.aar",
          "size": 246115,
          "sha512": "2f3aa757a6b4c3c6afd711d5b166eae2b2cf91048d01b36dc700d7b76cc9a6e91bc7c11157fa00809ef1a8448fbe77e3740edb65439f7eede9d4bf4742b0289e",
          "sha256": "b8eecd2803a9904194ed33e9293da983ffc6a8d04b36b8faca028b0bdc6ca4b1",
          "sha1": "4b572debc156f9da43579d14f9a74369eb9aeee0",
          "md5": "160238134b5fee8f688bd32b727ef6f8"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.virgilsecurity.sdk",
          "module": "sdk-android",
          "version": {
            "requires": "7.3.2"
          }
        },
        {
          "group": "com.virgilsecurity.sdk",
          "module": "crypto-android",
          "version": {
            "requires": "7.3.2"
          }
        },
        {
          "group": "com.virgilsecurity",
          "module": "pythia-android",
          "version": {
            "requires": "0.3.7"
          }
        },
        {
          "group": "com.virgilsecurity.crypto",
          "module": "pythia-android",
          "version": {
            "requires": "0.15.2"
          }
        },
        {
          "group": "com.virgilsecurity",
          "module": "ratchet-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ethree-common-2.0.9.aar",
          "url": "ethree-common-2.0.9.aar",
          "size": 246115,
          "sha512": "2f3aa757a6b4c3c6afd711d5b166eae2b2cf91048d01b36dc700d7b76cc9a6e91bc7c11157fa00809ef1a8448fbe77e3740edb65439f7eede9d4bf4742b0289e",
          "sha256": "b8eecd2803a9904194ed33e9293da983ffc6a8d04b36b8faca028b0bdc6ca4b1",
          "sha1": "4b572debc156f9da43579d14f9a74369eb9aeee0",
          "md5": "160238134b5fee8f688bd32b727ef6f8"
        }
      ]
    }
  ]
}
