{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.biometric",
    "module": "biometric-ktx",
    "version": "1.2.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "biometric-ktx-1.2.0-alpha05.aar",
          "url": "biometric-ktx-1.2.0-alpha05.aar",
          "size": 27119,
          "sha512": "61ae0ba5a93302b6bfd051e21e0ef453d675346afd950536ea8e2ff768c60fa96ba314ae92b9e4a3adf215f23fac41a48fe32322f207cfaf24d3ce7c04da151a",
          "sha256": "ecc46fdef74dac408fd988b3a49f7acea236649735b2d66c7568826c85a48dbd",
          "sha1": "27f99495a3ff081ba6f7d7d9e981734bbe8bb920",
          "md5": "15550e6699bb2c23f77786d94d094f84"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.biometric",
          "module": "biometric-ktx",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "biometric-ktx-1.2.0-alpha05.aar",
          "url": "biometric-ktx-1.2.0-alpha05.aar",
          "size": 27119,
          "sha512": "61ae0ba5a93302b6bfd051e21e0ef453d675346afd950536ea8e2ff768c60fa96ba314ae92b9e4a3adf215f23fac41a48fe32322f207cfaf24d3ce7c04da151a",
          "sha256": "ecc46fdef74dac408fd988b3a49f7acea236649735b2d66c7568826c85a48dbd",
          "sha1": "27f99495a3ff081ba6f7d7d9e981734bbe8bb920",
          "md5": "15550e6699bb2c23f77786d94d094f84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "biometric-ktx-1.2.0-alpha05-sources.jar",
          "url": "biometric-ktx-1.2.0-alpha05-sources.jar",
          "size": 11993,
          "sha512": "94fe7e304f6c0b79a483cbd171a7530425bb1d1e2a8db41f9a1de4d0d73928bae24184ef8e9812e3024e2b76e484bfc3f47a1c8e99e16ec38b5cfe569e6c836a",
          "sha256": "a172404e41322ee7d19ef86c418c1166af05426789f255726f39a2d8f9b2d1f1",
          "sha1": "2c9abcc5756ffa67461a98ed5d411588791afa54",
          "md5": "89d4df79bd3b01a55e47f6b7caa01432"
        }
      ]
    }
  ]
}