{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm",
    "module": "realm-annotations",
    "version": "10.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "realm-annotations-10.15.1.jar",
          "url": "realm-annotations-10.15.1.jar",
          "size": 5249,
          "sha512": "5edf85eb302da6424eacec613269eb5f1e8c4640c169578bfd97978c6efc5f0e4941cf0d2c1e454d85239bbfea037fceaddb736cdd1dcf0473212c5f05ff20a2",
          "sha256": "86051f4da908966a29392defaf1551ee96ab4b3d7cd8befa33f497a1bec87f58",
          "sha1": "0f7d9cd9aa6ab2b0769adac02f3799fb8e5272ea",
          "md5": "9fea77ff35c9d685200ed5803a2352f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "realm-annotations-10.15.1.jar",
          "url": "realm-annotations-10.15.1.jar",
          "size": 5249,
          "sha512": "5edf85eb302da6424eacec613269eb5f1e8c4640c169578bfd97978c6efc5f0e4941cf0d2c1e454d85239bbfea037fceaddb736cdd1dcf0473212c5f05ff20a2",
          "sha256": "86051f4da908966a29392defaf1551ee96ab4b3d7cd8befa33f497a1bec87f58",
          "sha1": "0f7d9cd9aa6ab2b0769adac02f3799fb8e5272ea",
          "md5": "9fea77ff35c9d685200ed5803a2352f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "realm-annotations-10.15.1-sources.jar",
          "url": "realm-annotations-10.15.1-sources.jar",
          "size": 13919,
          "sha512": "75221c77fe3bfbde6e7c60dc35ff4d07246e132da839661357a5efbe010a253ee6d5be086ca289f8b2ef33cbf96eeec472f8f149cfbdfe28720b4babd7c14889",
          "sha256": "d97fb6c0b8c558d82581fe25dda7b38029df99c983a12b3f385f0ea06e463e2b",
          "sha1": "de6f7ccce4f7ae174d6abc7025eea79f76eb45c0",
          "md5": "9a0075bd6d215f6b0c7c1a2339307e05"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "realm-annotations-10.15.1-javadoc.jar",
          "url": "realm-annotations-10.15.1-javadoc.jar",
          "size": 308929,
          "sha512": "99b0ef43c9ff6be3a6e252ea264493226a3585375edb67e2b097f149b157d9e98f6ae7dd63112a820c9796fe786a1fe778c692124a36976f68097c31ef42c2a5",
          "sha256": "07d418c17136fcb5da22eb6bccb1b4068f890f48d50d9926d2c50c8ce5988a44",
          "sha1": "72010bbe40e3fbcd9a6c662e4040ccb191a5dbb1",
          "md5": "892dd4fb86cd7168954ea46b2a6c2642"
        }
      ]
    }
  ]
}
