{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "7.0.2"
    }
  },
  "component" : {
    "group" : "com.github.3llomi",
    "module" : "RecordView",
    "version" : "3.1.3",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "releaseApiPublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "RecordView-3.1.3.aar",
      "url" : "RecordView-3.1.3.aar",
      "size" : 135318,
      "sha512" : "acc578e5d816830611ac78306ce91449f6fa2e2ff7084abcc5e8cb6e7cde2adccd49b6b72f13165bf0a0b3c788fc8d6786b457f6415cd7dd14f273f962b299eb",
      "sha256" : "d5149f770eb1fb0f0d7c5065df21284c5d23cff2a7b49e64e0fd972092b5183b",
      "sha1" : "1a5253f14330388bae949b90d64a99b556e67341",
      "md5" : "87f25c7676279a74e22edcb8ba2ac699"
    } ]
  }, {
    "name" : "releaseRuntimePublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "androidx.appcompat",
      "module" : "appcompat",
      "version" : {
        "requires" : "1.2.0"
      }
    }, {
      "group" : "io.supercharge",
      "module" : "shimmerlayout",
      "version" : {
        "requires" : "2.1.0"
      }
    } ],
    "files" : [ {
      "name" : "RecordView-3.1.3.aar",
      "url" : "RecordView-3.1.3.aar",
      "size" : 135318,
      "sha512" : "acc578e5d816830611ac78306ce91449f6fa2e2ff7084abcc5e8cb6e7cde2adccd49b6b72f13165bf0a0b3c788fc8d6786b457f6415cd7dd14f273f962b299eb",
      "sha256" : "d5149f770eb1fb0f0d7c5065df21284c5d23cff2a7b49e64e0fd972092b5183b",
      "sha1" : "1a5253f14330388bae949b90d64a99b556e67341",
      "md5" : "87f25c7676279a74e22edcb8ba2ac699"
    } ]
  } ]
}