{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-core",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "camera-core-1.2.3.aar",
          "url": "camera-core-1.2.3.aar",
          "size": 727209,
          "sha512": "ad4cdf99c38a894857f9380a54533c604c25833e67221989ec666ae9045dac4a93504f47add9847b6288ff11f1605dfa87fa98e4177c95f7e837074963e08da0",
          "sha256": "b4aeb070c0026cf15b0c24f60c72c5947c7e8ba48d392de6f5e3ecf188d5e3f7",
          "sha1": "063277e0d34a9eeec37429b38095850cc94fa47a",
          "md5": "c44d78ccf96ecaaeb81ea78d815169c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "camera-core-1.2.3.aar",
          "url": "camera-core-1.2.3.aar",
          "size": 727209,
          "sha512": "ad4cdf99c38a894857f9380a54533c604c25833e67221989ec666ae9045dac4a93504f47add9847b6288ff11f1605dfa87fa98e4177c95f7e837074963e08da0",
          "sha256": "b4aeb070c0026cf15b0c24f60c72c5947c7e8ba48d392de6f5e3ecf188d5e3f7",
          "sha1": "063277e0d34a9eeec37429b38095850cc94fa47a",
          "md5": "c44d78ccf96ecaaeb81ea78d815169c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-core-1.2.3-sources.jar",
          "url": "camera-core-1.2.3-sources.jar",
          "size": 543480,
          "sha512": "cb90a2e4406f68fa8c23a680f65b290168a79d1827d505f94ff95477e92999e1208f31210d4d4aacc3d83646dccb1a7c670456aa71ec4e87d8d47f1c78f1dab4",
          "sha256": "b2b5183b2c46d331460c330ff38baba04d799a98cf81b3d313a2cc9c15cc7f20",
          "sha1": "19ce2be951c2589d8ce5ce5d237470ad760e3e40",
          "md5": "5388c3faf24d4ef4a13129b23a0b1d68"
        }
      ]
    }
  ]
}