{
  "formatVersion": "1.1",
  "component": {
    "group": "com.virgilsecurity",
    "module": "pythia-android",
    "version": "0.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "m6aswqrgmbbq7ggw6izep6qveu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.virgilsecurity",
          "module": "pythia",
          "version": {
            "requires": "0.3.7"
          },
          "excludes": [
            {
              "group": "com.virgilsecurity.crypto",
              "module": "pythia"
            },
            {
              "group": "com.virgilsecurity.sdk",
              "module": "sdk"
            }
          ]
        },
        {
          "group": "com.virgilsecurity.sdk",
          "module": "sdk-android",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "com.virgilsecurity.crypto",
          "module": "pythia-android",
          "version": {
            "requires": "0.15.2"
          }
        },
        {
          "group": "com.virgilsecurity.crypto",
          "module": "foundation-android",
          "version": {
            "requires": "0.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "pythia-android-0.3.7.aar",
          "url": "pythia-android-0.3.7.aar",
          "size": 11248,
          "sha512": "3551fc6f9bb8becb55434d25ac3b0ecb286e75cbfd7f2be431b7c28a906f0766441a19529597b6ee531a008df2c8c4426420a01b0a98c0831db91932882f5ec3",
          "sha256": "9f8ce47b8749266f9cf6bfe8a410be368755cf7f590b31fda31da9d4585fa014",
          "sha1": "e8f23d89c5ddbb463c7ad68dedd8a6f1bd0ca6ef",
          "md5": "bed71bfc4f52b5e08e98f6b1da816d04"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.virgilsecurity",
          "module": "pythia",
          "version": {
            "requires": "0.3.7"
          },
          "excludes": [
            {
              "group": "com.virgilsecurity.crypto",
              "module": "pythia"
            },
            {
              "group": "com.virgilsecurity.sdk",
              "module": "sdk"
            }
          ]
        },
        {
          "group": "com.virgilsecurity.sdk",
          "module": "sdk-android",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "com.virgilsecurity.crypto",
          "module": "pythia-android",
          "version": {
            "requires": "0.15.2"
          }
        },
        {
          "group": "com.virgilsecurity.crypto",
          "module": "foundation-android",
          "version": {
            "requires": "0.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "pythia-android-0.3.7.aar",
          "url": "pythia-android-0.3.7.aar",
          "size": 11248,
          "sha512": "3551fc6f9bb8becb55434d25ac3b0ecb286e75cbfd7f2be431b7c28a906f0766441a19529597b6ee531a008df2c8c4426420a01b0a98c0831db91932882f5ec3",
          "sha256": "9f8ce47b8749266f9cf6bfe8a410be368755cf7f590b31fda31da9d4585fa014",
          "sha1": "e8f23d89c5ddbb463c7ad68dedd8a6f1bd0ca6ef",
          "md5": "bed71bfc4f52b5e08e98f6b1da816d04"
        }
      ]
    }
  ]
}
