{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm",
    "module": "realm-annotations-processor",
    "version": "10.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "realm-annotations-processor-10.15.1.jar",
          "url": "realm-annotations-processor-10.15.1.jar",
          "size": 209566,
          "sha512": "1d3e7f128139301266629b0a32688f3a040a3058172e418c67e51f7391c52be468198a335f3ccf6dda8ba4431fe9f526f2ce93ebbbfb7b73c048215ee5669d74",
          "sha256": "f32be527fccf7fb8424359d7a74b6d478a513b91454d17515097a7c4e38ce46f",
          "sha1": "4abf4aca3d7e8d7131f6fd69fb8e5d65ceff06c7",
          "md5": "ba29f1b6c0857bb526fdf635316ca86d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.15.1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "bson",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "realm-annotations-processor-10.15.1.jar",
          "url": "realm-annotations-processor-10.15.1.jar",
          "size": 209566,
          "sha512": "1d3e7f128139301266629b0a32688f3a040a3058172e418c67e51f7391c52be468198a335f3ccf6dda8ba4431fe9f526f2ce93ebbbfb7b73c048215ee5669d74",
          "sha256": "f32be527fccf7fb8424359d7a74b6d478a513b91454d17515097a7c4e38ce46f",
          "sha1": "4abf4aca3d7e8d7131f6fd69fb8e5d65ceff06c7",
          "md5": "ba29f1b6c0857bb526fdf635316ca86d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "realm-annotations-processor-10.15.1-sources.jar",
          "url": "realm-annotations-processor-10.15.1-sources.jar",
          "size": 79068,
          "sha512": "fcd00194784617214fc77bc59b2a36dfc01af5c7be7c1b6df7d25f8dd82d71c770492f115bbe3c2fbe31526cb26ca81c8a9c3c4e20dea6a9255ef1e87fea6114",
          "sha256": "85e3dbc76880be1526ec22d3d52e833bbfcd38a7115ee8313cd25973fb78209c",
          "sha1": "6adf47cf18f3e5d34417919b722718c53a139f59",
          "md5": "173db1f853a37a5e5fd3a566c0db1d10"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "realm-annotations-processor-10.15.1-javadoc.jar",
          "url": "realm-annotations-processor-10.15.1-javadoc.jar",
          "size": 281239,
          "sha512": "0d2965dd19472f4bee495cace6b8cf0b51d5069521a21024852787397a103f89ef99d1d769cda79d3748cc9fa2740eeb7c85f4ead5adecec97c926db14b9ecd4",
          "sha256": "f0fb354526b002af6cbff5390fb10bed473c23f8915ce68f17d4b66558d42ce5",
          "sha1": "6f931633286e24ec0796f4cad24f9c3bc43f3cd2",
          "md5": "1927102beb3c321c6706de73078d96cf"
        }
      ]
    }
  ]
}
