{
  "formatVersion": "1.1",
  "component": {
    "group": "com.virgilsecurity",
    "module": "ethree",
    "version": "2.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "gls4tuwsh5cexfdugromfow5wu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.virgilsecurity",
          "module": "ethree-common",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "ethree-2.0.9.aar",
          "url": "ethree-2.0.9.aar",
          "size": 10652,
          "sha512": "6f04a4656b66d56ed46eedb71ef74d062b8b6523a3091d5e949a8f1d0448f556778e9d8f31a80c216f45e9b37eb8cec1cf8e4eb4fb6219409cb974ae24f57ba6",
          "sha256": "9785298a72d29aef9241d07371bef75f9bc75dd04ef1ce9d543ab90b703679f1",
          "sha1": "0580989595d98b06756b37f362ed3c55efd2a37c",
          "md5": "0351c1601a3e8238fd28c04869c53216"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.virgilsecurity",
          "module": "ethree-common",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "ethree-2.0.9.aar",
          "url": "ethree-2.0.9.aar",
          "size": 10652,
          "sha512": "6f04a4656b66d56ed46eedb71ef74d062b8b6523a3091d5e949a8f1d0448f556778e9d8f31a80c216f45e9b37eb8cec1cf8e4eb4fb6219409cb974ae24f57ba6",
          "sha256": "9785298a72d29aef9241d07371bef75f9bc75dd04ef1ce9d543ab90b703679f1",
          "sha1": "0580989595d98b06756b37f362ed3c55efd2a37c",
          "md5": "0351c1601a3e8238fd28c04869c53216"
        }
      ]
    }
  ]
}
