{
  "formatVersion": "1.1",
  "component": {
    "group": "io.realm",
    "module": "realm-gradle-plugin",
    "version": "10.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "realm-gradle-plugin-10.15.1.jar",
          "url": "realm-gradle-plugin-10.15.1.jar",
          "size": 16495,
          "sha512": "1c8a70a0a81b3711d584d6dcf333720fb8b9fcf64343d21450e45b5ba29d621089ff3756b2335c088154bad3fd8bbd7a26a34bc78dfcebceaa4e01d85bab79e3",
          "sha256": "a1d1ee04aa75905aeac5c2d4fe1e8618f99b154e2d53f8351bc6d4d0f43a78e5",
          "sha1": "4360de78bd9c5d18b55421f313f26a35afe9dfc1",
          "md5": "9fbdb53f2e7431c06eba05d40a52d4f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-transformer",
          "version": {
            "requires": "10.15.1"
          }
        },
        {
          "group": "com.neenbedankt.gradle.plugins",
          "module": "android-apt",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "realm-gradle-plugin-10.15.1.jar",
          "url": "realm-gradle-plugin-10.15.1.jar",
          "size": 16495,
          "sha512": "1c8a70a0a81b3711d584d6dcf333720fb8b9fcf64343d21450e45b5ba29d621089ff3756b2335c088154bad3fd8bbd7a26a34bc78dfcebceaa4e01d85bab79e3",
          "sha256": "a1d1ee04aa75905aeac5c2d4fe1e8618f99b154e2d53f8351bc6d4d0f43a78e5",
          "sha1": "4360de78bd9c5d18b55421f313f26a35afe9dfc1",
          "md5": "9fbdb53f2e7431c06eba05d40a52d4f3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "realm-gradle-plugin-10.15.1-sources.jar",
          "url": "realm-gradle-plugin-10.15.1-sources.jar",
          "size": 4841,
          "sha512": "268b032c95089b5ea1e2a1df9732db0d91bdb52f014a6966a459061858041ba79d5859cd97c4e30ea265a30c88972cefcefeb35cf10412285a2f6bbcc7886c11",
          "sha256": "f35b16cd8b0491d4452ca8665f1bafe7cbcff444ec2346a0211e7a95e3c1a50c",
          "sha1": "33db0e879174ee702fb109aea418cabf595a09a7",
          "md5": "25fc8721e63d40e95a46b28e174f014f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "realm-gradle-plugin-10.15.1-javadoc.jar",
          "url": "realm-gradle-plugin-10.15.1-javadoc.jar",
          "size": 261,
          "sha512": "df8ae3243f3d39a7aa3dd581ef4a0209af013cbbff52e57eba099682b6799bbb1fa3e6ffc0e9ba8ef07cdc80ecaecff3ec7b50f87f3a1d7c6ff21717ac244118",
          "sha256": "3068ce2350d2ec93d77d408f8223dfeab169aa290c578d7b22624f47bbd53a7a",
          "sha1": "9ae05a6f30e7024bd81e17af1d4115947af88b53",
          "md5": "89ca7e1f8e6717cc2b9bc0b908871006"
        }
      ]
    }
  ]
}
