{
  "formatVersion": "1.1",
  "component": {
    "group": "io.michaelrocks",
    "module": "libphonenumber-android",
    "version": "8.13.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libphonenumber-android-8.13.7.aar",
          "url": "libphonenumber-android-8.13.7.aar",
          "size": 366182,
          "sha512": "324ea1aca5efca12445f8d0e71ead2d531844a637a43b424b3261fcde457a5f6bbf7cea06408aa8f9d5db71637d74ee195ad265ea6c6473a424617bf3318045d",
          "sha256": "5472a59d040b1c30c023b8c8d657f3c870d664c613fb4cd5fc84024d224a89e7",
          "sha1": "500b216cfd93fab57f8cb050da111496c1862cc2",
          "md5": "3dd98fb484f2fb763d8682bd7805c794"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libphonenumber-android-8.13.7.aar",
          "url": "libphonenumber-android-8.13.7.aar",
          "size": 366182,
          "sha512": "324ea1aca5efca12445f8d0e71ead2d531844a637a43b424b3261fcde457a5f6bbf7cea06408aa8f9d5db71637d74ee195ad265ea6c6473a424617bf3318045d",
          "sha256": "5472a59d040b1c30c023b8c8d657f3c870d664c613fb4cd5fc84024d224a89e7",
          "sha1": "500b216cfd93fab57f8cb050da111496c1862cc2",
          "md5": "3dd98fb484f2fb763d8682bd7805c794"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libphonenumber-android-8.13.7-sources.jar",
          "url": "libphonenumber-android-8.13.7-sources.jar",
          "size": 111656,
          "sha512": "7c5e0c77a231e57015a3365f25b5f0f5ccae44160827d24906c26508ad8f0cfb722a55a00e8a5ca8bb8a8f9d3f7dc02d235dd12011d6b1aa6e5ecb7c765d763a",
          "sha256": "11fb56ff32aaafc329b7db320c88939e5ead4c3594cd2b807e3b0ff0c9fd8d0e",
          "sha1": "bcfca02fc9bce31a9c67c324991f32f04b894584",
          "md5": "99ca33a062ec612c1f9cf27561182bfa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libphonenumber-android-8.13.7-javadoc.jar",
          "url": "libphonenumber-android-8.13.7-javadoc.jar",
          "size": 507533,
          "sha512": "95330b04ea4dcea3a86ac6066e25170315f697cac3a0c3e9d24af6f4a73189f2d2aeafc5f3ac42a0e4b7e9ef0fed4a732592e4202902fb821e4b8923bc94cb1a",
          "sha256": "4803e3caa61d2425b7891cc03fb4bba436f547572261484d698c7fd26006e772",
          "sha1": "c04fae7ad342796434d0815c6b7bdb47cbf22686",
          "md5": "e93ce0f0136354cf4413b1c5e0baa3a1"
        }
      ]
    }
  ]
}
