{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.biometric",
    "module": "biometric",
    "version": "1.2.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "biometric-1.2.0-alpha05.aar",
          "url": "biometric-1.2.0-alpha05.aar",
          "size": 245207,
          "sha512": "7360d157b77ace9bc720c67c446d468e6a85842668effdca93721551226b503cfbdd66067e19bc22f54842fa516662e7e1bd9f0e0a212b7c52bda60c09b2e1e8",
          "sha256": "9b3a8368e91562592bd3eaa3ce54fccbb5de2e35afceb9631f5c188eb131066f",
          "sha1": "a925edde5ba60408d09418b2839efbbfa720ae4b",
          "md5": "e8fc2939be8a3459ea67a913dce34a56"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.biometric",
          "module": "biometric-ktx",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "biometric-1.2.0-alpha05.aar",
          "url": "biometric-1.2.0-alpha05.aar",
          "size": 245207,
          "sha512": "7360d157b77ace9bc720c67c446d468e6a85842668effdca93721551226b503cfbdd66067e19bc22f54842fa516662e7e1bd9f0e0a212b7c52bda60c09b2e1e8",
          "sha256": "9b3a8368e91562592bd3eaa3ce54fccbb5de2e35afceb9631f5c188eb131066f",
          "sha1": "a925edde5ba60408d09418b2839efbbfa720ae4b",
          "md5": "e8fc2939be8a3459ea67a913dce34a56"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "biometric-1.2.0-alpha05-sources.jar",
          "url": "biometric-1.2.0-alpha05-sources.jar",
          "size": 70030,
          "sha512": "9a67b0f20e7b99b7aa21367cfcbbd8747b10692e4a4adeb7f97f10869605aee0fdd9e02218d76c4924aab65208ae8583fc347182b90235caa7424ff11cc4bf41",
          "sha256": "48395b813ba5a21d7c2b3314c37623c47d0d5e0c9bba3cc7f0d24d133688238c",
          "sha1": "bb9039b77fd65fdbf7aa84f8ec57236ba0c6d3b2",
          "md5": "b6f1a69ecc2f74a0e23a1bfa764361ff"
        }
      ]
    }
  ]
}