{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-view",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-view-1.2.3.aar",
          "url": "camera-view-1.2.3.aar",
          "size": 90043,
          "sha512": "11a0be3df9d3e34349e0e64912b0b4ff3051eaee498b5d137b013b51ff9fe0610acdf0392b670dc62ba21c46aa4bf1dd5a8a98b88dfda90c07cecbdb34de6466",
          "sha256": "08c0f162f75d859334e3233daaf4fcd9b80035bac8e9cd99b05681e4c68e1173",
          "sha1": "13834b453d2d2b79e1d21e617d6849dfbc371aa2",
          "md5": "fdd6008703a5c8a3e976656b21bc9640"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-view-1.2.3.aar",
          "url": "camera-view-1.2.3.aar",
          "size": 90043,
          "sha512": "11a0be3df9d3e34349e0e64912b0b4ff3051eaee498b5d137b013b51ff9fe0610acdf0392b670dc62ba21c46aa4bf1dd5a8a98b88dfda90c07cecbdb34de6466",
          "sha256": "08c0f162f75d859334e3233daaf4fcd9b80035bac8e9cd99b05681e4c68e1173",
          "sha1": "13834b453d2d2b79e1d21e617d6849dfbc371aa2",
          "md5": "fdd6008703a5c8a3e976656b21bc9640"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-view-1.2.3-sources.jar",
          "url": "camera-view-1.2.3-sources.jar",
          "size": 70874,
          "sha512": "4f5f4e8aa9c931f1f85d8dfd6aa6c065cd8981a9081eee10ef768468c12ba5f7e4725ec5c49049db32d9e8aefe257e447f985a71320eb82f5ac2c2b0b0fd5d29",
          "sha256": "7569a0b66d8c3fa8a4c08faf4983be84db499802bf7b27eaf112479c8cd8b721",
          "sha1": "9e704afef8cc2ad3f57a13fa7b35b2991f48499c",
          "md5": "dc81a75ad1a46b2227e4cc3888798d06"
        }
      ]
    }
  ]
}