{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.okhttp3",
    "module": "logging-interceptor",
    "version": "5.0.0-alpha.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-interceptor-5.0.0-alpha.11.jar",
          "url": "logging-interceptor-5.0.0-alpha.11.jar",
          "size": 16629,
          "sha512": "2db56fa4db440b12f6fe8d43ec828f783402785ba3065ca5834fee7ae63d9f9f5fde5d684bb94ab0a05e6dce958fe1af4cd29305aede4eb76f2ccb7635369ccf",
          "sha256": "bfac5db22a2f7cdaa878090777bfb91932f9be541581a441c57748b3860c6dc9",
          "sha1": "a1e022cc1c34f8f4b5b5539c2d128f83b0778f30",
          "md5": "301f008ac4ca37cd58ebec5df9b80e6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-interceptor-5.0.0-alpha.11.jar",
          "url": "logging-interceptor-5.0.0-alpha.11.jar",
          "size": 16629,
          "sha512": "2db56fa4db440b12f6fe8d43ec828f783402785ba3065ca5834fee7ae63d9f9f5fde5d684bb94ab0a05e6dce958fe1af4cd29305aede4eb76f2ccb7635369ccf",
          "sha256": "bfac5db22a2f7cdaa878090777bfb91932f9be541581a441c57748b3860c6dc9",
          "sha1": "a1e022cc1c34f8f4b5b5539c2d128f83b0778f30",
          "md5": "301f008ac4ca37cd58ebec5df9b80e6b"
        }
      ]
    }
  ]
}
