{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-lifecycle",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.2.3.aar",
          "url": "camera-lifecycle-1.2.3.aar",
          "size": 20265,
          "sha512": "c120e113408c563ebb2a1d001988bac3b10503496b35b4967dd1708609b7a9c657f8591b182153024d29d74a111ac35c9c8819f15ec5a6d0fe8a4a0ce2b077d1",
          "sha256": "899f45a21a81eaea2e2291bb4f4061c3afe2ea3df474cc1fedc94b6940a719cb",
          "sha1": "0f1ce65715de4b002d670a86b708a739b27afb35",
          "md5": "ef3b190ed46b869151e205b067d43c2c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.2.3.aar",
          "url": "camera-lifecycle-1.2.3.aar",
          "size": 20265,
          "sha512": "c120e113408c563ebb2a1d001988bac3b10503496b35b4967dd1708609b7a9c657f8591b182153024d29d74a111ac35c9c8819f15ec5a6d0fe8a4a0ce2b077d1",
          "sha256": "899f45a21a81eaea2e2291bb4f4061c3afe2ea3df474cc1fedc94b6940a719cb",
          "sha1": "0f1ce65715de4b002d670a86b708a739b27afb35",
          "md5": "ef3b190ed46b869151e205b067d43c2c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-lifecycle-1.2.3-sources.jar",
          "url": "camera-lifecycle-1.2.3-sources.jar",
          "size": 17337,
          "sha512": "cf0398c7c6ec7515f6ed522c0d01e06605626f3301abd93f303b861c315b62b30b230addb81355219310e93212a51df6cf49f3a0d93b9af1b817cb9960e638c4",
          "sha256": "c5b07109d2e7fb4b0b362eaa1f5bea12c309a4eb6ca782274b59071dae2d879f",
          "sha1": "207884d7016947db3582f2bfc8f2073a390745ff",
          "md5": "b7b6068d83aba5939fd5ab2c5cac3e74"
        }
      ]
    }
  ]
}